logging:
  level:
    root: info
  charset:
    console: UTF-8
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(pzP8ytshlucDNTKaXss2ErtUH0JnHZdbiZMttMb5GAkuAN4S6TwoU2eMQMAU6yOJjOYZkrGs5GXpsWO1PGLiA0h/Fi2LcQXzyO3EZ+yZvLWlYouB29xuxCXXV577opih1/MgFOsP9nMNDPTjAPETMQ==)
    username: ENC(bKRGejZpI8TMFjih7jxt1A==)
    password: ENC(qE4NWADO/zcI0oK+NP9bwg==)
  sql:
    init:
      mode: always
common:
  jwt:
    secret_key: ENC(B7fG6cE60meF84F+zLPkgmVanY1+wKuLxkFT5dyboQM=)
    expire_time: 360000