server:
  port: 8080
spring:
  datasource:
    hikari:
      connection-timeout: 5000
      validation-timeout: 1000
      maximum-pool-size: 10
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/META-INF/mybatis/*.xml
jasypt:
  encryptor:
    bean: jasyptStringEncryptor