server:
  port: 8080
  shutdown: graceful
spring:
  datasource:
    hikari:
      connection-timeout: 5000
      validation-timeout: 1000
      maximum-pool-size: 10
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/META-INF/mybatis/*.xml
  type-aliases-package: com.spring.java.dto
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
management:
  endpoints:
    web:
      exposure:
        include: "*"