logging:
  level:
    root: info
  charset:
    console: UTF-8
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(XN5lSt7y+AyhfL2alga1pRkU1SVl3nlU2qNiFk/joPP63PgEXggl5UsPI3XRogs+dz9mt0Q1JFMlCUJH2trIIYIVOaGdCjM0ECdOUwG/as3pATfynXAo6Q==)
    username: ENC(bKRGejZpI8TMFjih7jxt1A==)
    password: ENC(qE4NWADO/zcI0oK+NP9bwg==)
  sql:
    init:
      mode: always
common:
  jwt:
    secret_key: ENC(B7fG6cE60meF84F+zLPkgmVanY1+wKuLxkFT5dyboQM=)
    expire_time: 360000